export enum Routes {
  About = '/about',
  Account = '/account',
  MyRentals = '/rentals',
  Booking = '/booking/:id',
  CreateProduct = '/createProduct',
  BecomeHost = '/becomeHost',
  ForgotPassword = '/forgotPassword',
  Home = '/',
  Products = '/products',
  Product = '/products/:id',
  Payment = '/payment/:id',
  SuccessPayment = '/successPayment',
  SignIn = '/signin',
  SignUp = '/signup',
  EditProduct = '/edit/products/:id',
  Historic = '/historic',
  Refund = '/refund/:id',
  GovDue = '/govDue/',
  SuccessRefund = '/successrefund',
  OwnerRefund = '/ownerrefund/:id',
}
